# Generated by Django 5.1.3 on 2024-12-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating_bot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], default=1, max_length=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
