# Generated by Django 5.1.3 on 2024-12-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating_bot", "0002_remove_user_is_active_user_age_user_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
