# Generated by Django 5.1.3 on 2024-12-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dating_bot", "0003_alter_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
    ]
