# Generated by Django 5.1.3 on 2024-12-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating_bot", "0006_match_interaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
